name: Baseball Hit Predictor
baseurl: MLB-hit-predictor
navbar:
  title: "Baseball Hit Predictor"
  left:
  - text: Blog
    menu:
    - text: BlogPost1
      href: index.html
    - text: blogpost2
      href: index.html
  - text: Research & Methodology 
    href: index.html
  right:
  - text: About
    href: index.html
  - text: Data Visualizations
    href: index.html
output:
  html_document
output_dir: docs

