title: Hit Prediction Project
description: ⚾ Data science project to predict if a Major League Baseball player will get a hit on any given day ⚾
# output:
#  html_document
# output_dir: docs
# logo:  ./docs/images/home_image1.png
theme: jekyll-theme-minimal
destination: public
