name: GEOG 4/590
navbar:
  title: "GEOG 4/590:  R for Earth-System Science"
  left:
  - text: Topics
    menu:
    - text: Introduction
      href: intro.html
    - text: Raster mapping example
      href: plot_alpha_RMarkdown_Site.html
  right:
  - text: About
    href: about.html
output:
  html_document
output_dir: docs
